### ISSUE TITLE
Update Pygments to latest version

### ISSUE THREAD

**Issue by vayn** [Vim-cn/Vinergy#3]
旧版不支持 Rust，看这里： http://p.vim-cn.com/cbP7?rs
该升级了 :smile: @lilydjwg

**Comment by lilydjwg** [comment]
又好久没升级了= =

你写 rust 就有高亮啦，虽然不太对……升级了之后还是不认 rs 的……

用 cfp.vim-cn.com 这个域名的话，支持 https 和 IPv6 的哦～https://cfp.vim-cn.com/cbP8/rust

**Comment by vayn** [comment]
好棒，以后就用 `cfp` 了。用 rust 也可以，就是不能偷懒，另外高亮确实还有点问题……
改进后的「猜数字」应该会比我之前的版本存活时间更长吧  :stuck_out_tongue_closed_eyes:
